version: "3"
services:
  db:
    image: postgres:9.6-stretch
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: authenticate
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  web:
    build: .
    command: "go run ./cmd/api"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  migrations:
    build: .
    command: "go run ./cmd/migrations"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    depends_on:
      - db
    env_file:
      - .env
