version: "3"
services:
  authenticate-db:
    image: postgres:9.6-stretch
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: authenticate
    ports:
      - "5432:5432"

  web:
    build: .
    command: "go run ./cmd/api"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - authenticate-db
    env_file:
      - .env

  migrations:
    build: .
    command: "go run ./cmd/migrations"
    volumes:
      - .:/app
    depends_on:
      - authenticate-db
    env_file:
      - .env
