name: CD (Production)
on:
  workflow_run:
    workflows: [Test Code]
    types:
      - completed
    branches: [testing-ci-cd]

jobs:
  copy_dags:
    name: 'Test CD'
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2